# SERVER
server.port=8080


# DATABASE (POSTGRESQL)
spring.datasource.url=jdbc:postgresql://localhost:5433/loanapp
spring.datasource.username=postgres
spring.datasource.password=him123
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.open-in-view=false


# MAILTRAP SANDBOX (OTP EMAIL)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=6cfd97aafb911e
spring.mail.password=f2c57c35c7c19e

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# JWT
jwt.secret=dev-secret-key-change-in-prod-32chars
jwt.expiration=3600000
jwt.refresh.expiration=604800000


# LOGGING (TEMP FOR DEBUG)
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.web=INFO
logging.level.root=INFO
